{
 "title": "Waterlilies",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Metered Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"time\", '5m'),\n  device_id,\n  avg(power_total_active)\nFROM\n  meter_readings\nWHERE\n  $__timeFilter(\"time\")\nAND device_id != '024306e6-f276-4233-9550-7b1ea69c1f37'\nGROUP BY\n  time,\n  device_id\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Metered Power Stacked - BUGGY FOR NEGATIVE VALUES",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5m', time) AS time_b,\n  device_id,\n  AVG(power_total_active)\nFROM meter_readings \nWHERE $__timeFilter(time) AND device_id != '7e2b6ad8-662f-4d31-96b6-fe72d102468a' AND device_id != '024306e6-f276-4233-9550-7b1ea69c1f37'\nGROUP BY time_b, device_id\nORDER BY time_b"
    }
   ]
  },
  {
   "title": "PowerPack",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\", '5m'), avg(soe) as avg_soe, avg(target_power) as avg_target_power FROM bess_readings WHERE $__timeFilter(\"time\") GROUP BY time ORDER BY time\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(\"time\", '5m'),\n  device_id,\n  avg(power_total_active) as emulated_site_power\nFROM\n  meter_readings\nWHERE\n  $__timeFilter(\"time\")\nAND device_id = '024306e6-f276-4233-9550-7b1ea69c1f37'\nGROUP BY\n  time,\n  device_id\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Site Energy Exports",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\", '5m'), avg(energy_exported_active) as export, device_id FROM meter_readings WHERE $__timeFilter(\"time\") AND device_id='7e2b6ad8-662f-4d31-96b6-fe72d102468a' GROUP BY time, device_id ORDER BY time\n"
    }
   ]
  },
  {
   "title": "Site Energy Imports",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\", '5m'), avg(energy_imported_active) as import, device_id FROM meter_readings WHERE $__timeFilter(\"time\") AND device_id='7e2b6ad8-662f-4d31-96b6-fe72d102468a' GROUP BY time, device_id ORDER BY time\n"
    }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\", '5m'), avg(frequency) AS avg_frequency FROM meter_readings WHERE $__timeFilter(\"time\") GROUP BY 1 ORDER BY 1"
    }
   ]
  }
 ]
}