meters:
  acuvim2:
    "Mains incomer":
      id: 7e2b6ad8-662f-4d31-96b6-fe72d102468a
      host: 192.168.8.110:502
      pollIntervalSecs: 2
      pt1: 400
      pt2: 400
      ct1: 800
      ct2: 5
    "Tesla battery inverter":
      id: 4ec0bbfd-c07e-4871-b5b6-ead7dfc1adf5
      host: 192.168.8.111:502
      pollIntervalSecs: 2
      pt1: 400
      pt2: 400
      ct1: 400
      ct2: 5
    "Housing feeder 1 meter":
      id: f8db31ad-f017-4953-bff5-8e1456f08e38
      host: 192.168.8.112:502
      pollIntervalSecs: 2
      pt1: 400
      pt2: 400
      ct1: 400
      ct2: 5
    "Housing feeder 2 meter":
      id: 4032e6d5-65f9-43d5-85c3-a9d100a5de7a
      host: 192.168.8.114:502
      pollIntervalSecs: 2
      pt1: 400
      pt2: 400
      ct1: 400
      ct2: 5
    "Future EV pillar supply":
      id: 35aad38a-d9c9-4bd1-a9f1-88f0bee388bb
      host: 192.168.8.113:502
      pollIntervalSecs: 2
      pt1: 400
      pt2: 400
      ct1: 400
      ct2: 5

bess:
  powerPack:
    host: 192.168.8.130:502
    id: 6340b165-1da2-48af-9b33-891e443b1695
    pollIntervalSecs: 2
    nameplatePower: 222
    nameplateEnergy: 444
    teslaOptions:
      inverterRampRateUp: 50
      inverterRampRateDown: 50
      alwaysActive: false

dataPlatforms:
- # QA supabase
  uploadIntervalSecs: 60
  supabase:
    url: https://rkzgrxssutcwrauaazjz.supabase.co
    schema: flows
    anonKeyEnvVar: SUPABASE_ANON_KEY_QA
    userKeyEnvVar: SUPABASE_USER_KEY_QA
- # Prod supabase
  uploadIntervalSecs: 60
  supabase:
    url: https://pqlwxerasppsyleweruk.supabase.co
    schema: flows
    anonKeyEnvVar: SUPABASE_ANON_KEY_PROD
    userKeyEnvVar: SUPABASE_USER_KEY_PROD

controller:
  siteMeter: 7e2b6ad8-662f-4d31-96b6-fe72d102468a
  bessMeter: 4ec0bbfd-c07e-4871-b5b6-ead7dfc1adf5
  emulation:
    bessIsEmulated: false
    emulatedSiteMeter: null
  bessChargeEfficiency: 0.85
  bessSoeMin: 20
  bessSoeMax: 366
  bessChargePowerLimit: 222
  bessDischargePowerLimit: 100
  siteImportPowerLimit: 140
  siteExportPowerLimit: 230
  controlComponents:
    importAvoidanceWhenShort:
      - shortPrediction:
          allowPrediction: true
          volumeCutoff: 150000
          timeCutoffSecs: 900  # 15mins
        period:
          days: weekends:Europe/London
          start: 07:00:00:Europe/London
          end: 19:00:00:Europe/London
    importAvoidance:
      # Activate import avoidance during weekday evening peaks
      - days: weekdays:Europe/London
        start: 17:00:00:Europe/London
        end: 19:00:00:Europe/London
    exportAvoidance:
      # Activate export avoidance when we can be noisy
      - days: weekdays:Europe/London
        start: 07:00:00:Europe/London
        end: 17:00:00:Europe/London
      - days: weekends:Europe/London
        start: 07:00:00:Europe/London
        end: 19:00:00:Europe/London
    chargeToSoePeriods: []
    dischargeToSoePeriods: []
    dynamicPeakDischarge: []
      # - 
      #   period:
      #     days: weekdays:Europe/London
      #     start: 17:00:00:Europe/London
      #     end: 19:00:00:Europe/London
      #   targetSoe: 20
      #   targetShortPeriods: true
      #   shortPrediction:
      #     allowPrediction: true
      #     volumeCutoff: 0
      #     timeCutoffSecs: 1200  # 20mins
      #   prioritiseResidualLoad: true
    dynamicPeakApproach:
      # Make sure the battery has enough charge for import avoidance over the evening peak
      - 
        peakPeriod:
          days: weekdays:Europe/London
          start: 17:00:00:Europe/London
          end: 17:00:01:Europe/London
        toSoe: 0
        encourageToSoe: 200
        assumedChargePower: 100
        forceChargeDurationFactor: 1.25
        encourageChargeDurationFactor: 2.5
        chargeCushionMins: 180
        longPrediction:
          allowPrediction: true
          volumeCutoff: 150000
          timeCutoffSecs: 900
    nivChase:
      - period:
          days: weekdays:Europe/London
          start: 05:30:00:Europe/London
          end: 17:00:00:Europe/London
        niv:
          chargeCurve:
              points: [
                { "x": -999999, "y": 366 },
                { "x": 4, "y": 366 },
                { "x": 6, "y": 350 },
                { "x": 16, "y": 0 }
              ]
          dischargeCurve:
            points: [
              { "x": 25, "y": 366 },
              { "x": 35, "y": 200 },
              { "x": 55, "y": 100 },
              { "x": 100, "y": 0 },
              { "x": 9999999, "y": 0 }
            ]
          curveShiftLong: 4
          curveShiftShort: 0
          defaultPricing: []
          pricePrediction:
            whenShort:
              allowPrediction: true
              volumeCutoff: 250000
              timeCutoffSecs: 900
            whenLong:
              allowPrediction: true
              volumeCutoff: 150000
              timeCutoffSecs: 900
      - period:
          days: weekends:Europe/London
          start: 07:00:00:Europe/London
          end: 19:00:00:Europe/London
        niv:
          chargeCurve:
              points: [
                { "x": -999999, "y": 366 },
                { "x": -2, "y": 366 },
                { "x": 6, "y": 65 },
                { "x": 16, "y": 0 }
              ]
          dischargeCurve:
            points: [
              { "x": 8, "y": 366 },
              { "x": 14, "y": 65 },
              { "x": 55, "y": 30 },
              { "x": 999999, "y": 0 }
            ]
          curveShiftLong: 2
          curveShiftShort: 2
          defaultPricing: []
          pricePrediction:
            whenShort:
              allowPrediction: true
              volumeCutoff: 250000
              timeCutoffSecs: 900
            whenLong:
              allowPrediction: true
              volumeCutoff: 150000
              timeCutoffSecs: 900

  ratesImport:
    - # Unify supplier import
      rate: 1
      periods:
        - days: all:Europe/London
          start: 00:00:00:Europe/London
          end: 23:59:59:Europe/London
    - # Final consumption levies
      rate: 1.8  # This accounts for BSUoS at 1.29p/kWh and assumes a NCSP of 0.9 for the remaining fees for 0.5p/kWh
      periods:
        - days: all:Europe/London
          start: 00:00:00:Europe/London
          end: 23:59:59:Europe/London
    - # DUoS red import
      rate: 10.983
      periods:
        - days: weekdays:Europe/London
          start: 17:00:00:Europe/London
          end: 19:00:00:Europe/London
    - # DUoS amber import
      rate: 0.499
      periods:
        - days: weekdays:Europe/London
          start: 07:30:00:Europe/London
          end: 17:00:00:Europe/London
        - days: weekdays:Europe/London
          start: 19:00:00:Europe/London
          end: 21:30:00:Europe/London
        - days: weekends:Europe/London
          start: 16:30:00:Europe/London
          end: 19:30:00:Europe/London
    - # DUoS green import
      rate: 0.034
      periods:
        - days: weekdays:Europe/London
          start: 00:00:00:Europe/London
          end: 07:30:00:Europe/London
        - days: weekdays:Europe/London
          start: 21:30:00:Europe/London
          end: 23:59:59:Europe/London
        - days: weekends:Europe/London
          start: 00:00:00:Europe/London
          end: 16:30:00:Europe/London
        - days: weekends:Europe/London
          start: 19:30:00:Europe/London
          end: 23:59:59:Europe/London
  ratesExport:
    - # DUoS red export
      rate: -10.4
      periods:
        - days: weekdays:Europe/London
          start: 17:00:00:Europe/London
          end: 19:00:00:Europe/London
    - # DUoS amber export
      rate: -0.52
      periods:
        - days: weekdays:Europe/London
          start: 07:30:00:Europe/London
          end: 17:00:00:Europe/London
        - days: weekdays:Europe/London
          start: 19:00:00:Europe/London
          end: 21:30:00:Europe/London
        - days: weekends:Europe/London
          start: 16:30:00:Europe/London
          end: 19:30:00:Europe/London
    - # DUoS green export
      rate: -0.037
      periods:
        - days: weekdays:Europe/London
          start: 00:00:00:Europe/London
          end: 07:30:00:Europe/London
        - days: weekdays:Europe/London
          start: 21:30:00:Europe/London
          end: 23:59:59:Europe/London
        - days: weekends:Europe/London
          start: 00:00:00:Europe/London
          end: 16:30:00:Europe/London
        - days: weekends:Europe/London
          start: 19:30:00:Europe/London
          end: 23:59:59:Europe/London
