{
 "title": "Microgrid Overview",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "SELECT DISTINCT site from marcus.device_registry"
   }
  ]
 },
 "panels": [
  {
   "title": "Metered Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_b,\n  device_registry.name,\n  power_total_active_avg as power\nFROM\n  marcus.meter_readings_5m\nINNER JOIN marcus.device_registry ON device_registry.device_id=meter_readings_5m.device_id\nWHERE\n  $__timeFilter(\"time_b\")\n  AND meter_readings_5m.device_id != '024306e6-f276-4233-9550-7b1ea69c1f37'\n  AND device_registry.site = '$site'\nORDER BY\n  time_b"
    }
   ]
  },
  {
   "title": "Tesla BESS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_b,\n  soe_avg as avg_soe,\n  target_power_avg as avg_target_power\nFROM\n  bess_readings_5m\nWHERE\n  $__timeFilter(\"time_b\")\n  AND device_id IN (\n    SELECT\n      device_id\n    from\n      marcus.device_registry\n    where\n      site = '$site'\n  )\nORDER BY\n  time_b"
    },
    {
     "rawSql": "SELECT\n  time_b,\n  device_id,\n  power_total_active_avg as emulated_site_power\nFROM\n  meter_readings_5m \nWHERE\n  $__timeFilter(\"time_b\")\n  AND\n  device_id = (\n    SELECT device_id from marcus.device_registry where site='$site' AND name='Emulated site meter'\n  )\nORDER BY\n  time_b"
    }
   ]
  },
  {
   "title": "Metered Energy Stacked",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_b,\n  device_registry.name,\n  energy_imported_active_delta as import,\n  energy_exported_active_delta as export\nFROM\n  marcus.meter_readings_5m\nINNER JOIN marcus.device_registry ON device_registry.device_id=meter_readings_5m.device_id\nWHERE\n  $__timeFilter(time_b)\n  AND device_registry.site = '$site'\n  AND device_registry.type = 'meter'\nORDER BY\n  time_b"
    }
   ]
  },
  {
   "title": "Site Cumulative Energy",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_b,\n  energy_imported_active_min as import,\n  energy_exported_active_min as export,\n  device_id\nFROM\n  meter_readings_5m \nWHERE\n  $__timeFilter(\"time_b\")\n  AND device_id = (\n    SELECT device_id from marcus.device_registry where site='$site' AND name='Main incomer'\n  )\nORDER BY\n  time_b"
    }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_b,\n  frequency_avg AS avg_frequency\nFROM\n  meter_readings_5m\nWHERE\n  $__timeFilter(\"time_b\")\n  AND device_id = (\n    SELECT device_id from marcus.device_registry where site='$site' AND name='Main incomer'\n  )\nORDER BY\n  time_b"
    }
   ]
  }
 ]
}